### PR TITLE
[PLAT-223] Add chain to discovery docker compose

### PR DESCRIPTION
**Pull request by raymondjacobson**
Adds optional `--chain` flag to discovery node setup.

```
./discovery-provider/chain/make_genesis.sh
audius-cli launch discovery-provider --chain
```

This will update the chain spec to make your delegate wallet the initial gensis sealer, and then you get stuff like this:
Screen Shot 2022-07-08 at 6 22 06 PM

For full productionization/staging:
- Chainspec needs to be updated with bootnodes
- Chainspec needs to be updated with genesis of one of the public keys of the known discovery nodes
- The other changes to discovery to modify the sealer list as we go. More on that to come...

Hopefully I followed the relevant conventions, but @cheran-senthil, pls tell me if you want me to change something :)

### CODE REVIEW

**Comment by cheran-senthil** [comment]
Small comment, we should generate spec.json from python instead of bash, other than that, everything looks good!

**Comment by raymondjacobson** [comment]
> Small comment, we should generate spec.json from python instead of bash, other than that, everything looks good!

even if we want to use jq? the instructions are mostly taken from the docs here https://docs.nethermind.io/nethermind/ethereum-client/private-networks/how-to-setup-a-nethermind-only-clique-based-chain

**Comment by raymondjacobson** [comment]
> > Small comment, we should generate spec.json from python instead of bash, other than that, everything looks good!
> 
> even if we want to use jq? the instructions are mostly taken from the docs here https://docs.nethermind.io/nethermind/ethereum-client/private-networks/how-to-setup-a-nethermind-only-clique-based-chain

FWIW also I could not check this in. No one will need to run this besides us once. Figure it would be nice to have more "automation" though.

**Comment by cheran-senthil** [comment]
I think it would still be better to use python.

Instead of calling `jq` from python we can just use python's built-in json library

I agree there is not much concern here, I just dislike having scripts scattered in the repo

**Comment by raymondjacobson** [comment]
> I think it would still be better to use python.
> 
> Instead of calling `jq` from python we can just use python's built-in json library
> 
> I agree there is not much concern here, I just dislike having scripts scattered in the repo

Switched to python with some generalized CLI stuff. Seems a bit overkill, but we can use it for other chainspec utils, like updating bootnodes.

**Comment by cheran-senthil** [comment]
We can move this to within audius-cli, can follow up with another PR too

**Pull request merged**
